plugins { id 'com.android.application'     buildTypes {
        release { minifyEnabled false }
    }
}

android {
    namespace 'com.example.carromaim'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.carromaim'
        minSdk 23
        targetSdk 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
        versionCode 1
        versionName '1.0'
    }
}
